version: "3"

services:
  heimdall:
    container_name: heimdall
    image: ghcr.io/linuxserver/heimdall
    networks:
      - traefiknet
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      # TODO: move to e.g. NFS mount
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.${DOMAIN_NAME?}`)"
      - "traefik.http.routers.heimdall.tls=true"

networks:
  traefiknet:
    external: true
