# Refs
# - https://github.com/docker-library/docs/blob/master/influxdb/README.md
# - https://github.com/jkehres/docker-compose-influxdb-grafana
# - https://grafana.com/docs/grafana/latest/administration/provisioning/
# - https://dev.to/project42/install-grafana-influxdb-telegraf-using-docker-compose-56e9
# - https://github.com/InfluxGraph/influxgraph/blob/master/docker/compose/docker-compose.yml
# - https://github.com/docker-library/docs/blob/master/influxdb/README.md#using-this-image---influxdb-1x
#
# TrueNAS Refs:
# - https://github.com/cucac/truenas-influxdb-grafana
# - https://www.truenas.com/community/threads/guide-to-setting-up-grafana-influxdb-metrics.88943/
# - https://github.com/lapo-luchini/grafana-truenas
#

# TODO
# - persistent volume for influxdb and grafana, is NFS overkill? i think yes
# - auth and reverse proxy for influxdb?
# - traefik stats
# - pihole stats
# - containers stats
# - stats for apps within containers
# - smb stats
#
version: "3"

volumes:
  storage-influxdb:
  storage-grafana:

services:
  influxdb:
    image: influxdb:1.8
    restart: always
    volumes:
      - storage-influxdb:/var/lib/influxdb
    networks:
      - traefiknet
    environment:
      # TODO: clean up auth, see ref above
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_GRAPHITE_ENABLED=true
      # TODO: make multiline work, ref: INFLUXDB_GRAPHITE_0_TEMPLATES_0
      - INFLUXDB_GRAPHITE_TEMPLATES=*.app env.service.resource.measurement,servers.* .host.resource.measurement.field*
    ports:
      - 8086:8086
      - 2003:2003

  grafana:
    image: grafana/grafana:8.2.5
    restart: always
    volumes:
      - storage-grafana:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - influxdb
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`mon.${DOMAIN_NAME?}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.services.grafana.loadbalancer.server.port=3000"

networks:
  traefiknet:
    external: true
