version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      # Documentation: https://github.com/pi-hole/docker-pi-hole
      TZ: "Europe/Berlin"
      # WEBPASSWORD: TODO
      # To enable hostname resolution of local devices
      # WARNING: this is specific to my home network
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: "lan"
      REV_SERVER_TARGET: "10.0.1.1"  # router address
      REV_SERVER_CIDR: "10.0.1.0/24"
    networks:
      - traefiknet
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      # 80/tcp --> web interface
      - "traefik.http.routers.pihole.rule=Host(`pihole.lan`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # 53/tcp
      - "traefik.tcp.routers.53-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.53-tcp.entrypoints=53-tcp"
      - "traefik.tcp.routers.53-tcp.service=pihole-53-tcp"
      - "traefik.tcp.services.pihole-53-tcp.loadbalancer.server.port=53"
      # 53/udp
      - "traefik.udp.routers.53-udp.entrypoints=53-udp"
      - "traefik.udp.routers.53-udp.service=pihole-53-udp"
      - "traefik.udp.services.pihole-53-udp.loadbalancer.server.port=53"
      # 67/udp --> for DHCP, handled in my router, not needed here
      # 443/tcp --> https ads? TODO: findout

networks:
  traefiknet:
    external: true
