version: "3"

# Based on:
#   - https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml
#   - https://goneuland.de/nextcloud-server-mit-docker-compose-und-traefik-installieren/#6_Optimierungen
#
# Full documentation on github
#
# Nextcloud CLI:
#   docker-compose exec --user www-data app php occ
#
# TODO:
#   - test NFS volumes
#   - fix reverse proxy settings for apache (nextcloud admin > overview)
#   - stress test

# volumes:
#   nextcloud-webroot:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: "addr=${NFS_ADDR},nolock,soft,rw"
#       device: ":${NFS_PATH_WEBROOT}"
#   nextcloud-userdata:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: "addr=${NFS_ADDR},nolock,soft,rw"
#       device: ":${NFS_PATH_USERDATA}"
#   nextcloud-db:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: "addr=${NFS_ADDR},nolock,soft,rw"
#       device: ":${NFS_PATH_DB}"

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - nextcloud_internal
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud_internal

  cron:
    image: nextcloud:apache
    restart: always
    networks:
      - nextcloud_internal
    volumes:
      - ./nextcloud-webroot:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  app:
    image: nextcloud:apache
    restart: always
    networks:
      - nextcloud_internal
      - traefiknet
    depends_on:
      - db
      - redis
    volumes:
      - ./nextcloud-webroot:/var/www/html
      - ./nextcloud-userdata:/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${TRAEFIK_ADDRESS}
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN}
      - OVERWRITEPROTOCOL=https
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefiknet"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud-dav.redirectRegex.permanent=true"
      - "traefik.http.middlewares.nextcloud-dav.redirectRegex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-dav.redirectRegex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-sts.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.nextcloud-sts.headers.stspreload=true"
      - "traefik.http.middlewares.nextcloud-sts.headers.stsseconds=31536000"
      - "traefik.http.middlewares.nextcloud-sts.headers.isdevelopment=false"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,nextcloud-sts"

networks:
  traefiknet:
    external: true
  nextcloud_internal:
    internal: true
