version: "3"

# Based on:
#   - https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml
#   - https://goneuland.de/nextcloud-server-mit-docker-compose-und-traefik-installieren/#6_Optimierungen
#
# Full documentation on Nextcloud's github
#
# Nextcloud CLI:
#   docker-compose exec --user www-data app php occ
#
# Usage:
#  - `mkdir webroot`
#  - copy sample.env to .env, and edit content accordingly
#  - make sure folders defined for "NC_PATH*" are created and has UID of 33
#
# To update:
#   docker-compose down
#   docker-compose pull
#   docker-compose up -d
#

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${NC_PATH_DB?}:/var/lib/mysql
    networks:
      - nextcloud_internal
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?}
      - MYSQL_DATABASE=${MYSQL_DATABASE?}
      - MYSQL_USER=${MYSQL_USER?}

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - nextcloud_internal

  cron:
    image: nextcloud:24-apache
    restart: always
    networks:
      - nextcloud_internal
    volumes:
      - ${NC_PATH_USERDATA?}:/data
      - ./webroot:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    environment:
      - NEXTCLOUD_DATA_DIR=/data

  app:
    image: nextcloud:24-apache
    restart: always
    networks:
      - nextcloud_internal
      - traefiknet
    depends_on:
      - db
      - redis
    volumes:
      - ${NC_PATH_USERDATA?}:/data
      - ./webroot:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN?}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${TRAEFIK_ADDRESS?}
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN}
      - OVERWRITEPROTOCOL=https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN?}`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud-dav.redirectRegex.permanent=true"
      - "traefik.http.middlewares.nextcloud-dav.redirectRegex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-dav.redirectRegex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-sts.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.nextcloud-sts.headers.stspreload=true"
      - "traefik.http.middlewares.nextcloud-sts.headers.stsseconds=31536000"
      - "traefik.http.middlewares.nextcloud-sts.headers.isdevelopment=false"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,nextcloud-sts"

networks:
  traefiknet:
    external: true
  nextcloud_internal:
    internal: true
