version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    container_name: portainer
    networks:
      - proxynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lan`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"

      ## from: https://documentation.portainer.io/v2.0/ad/traefik/rp-traefik/
      # # Frontend
      # - "traefik.enable=true"
      # - "traefik.http.routers.frontend.rule=Host(`portainer.lan`)"
      # - "traefik.http.routers.frontend.entrypoints=websecure"
      # - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      # - "traefik.http.routers.frontend.service=frontend"
      # - "traefik.http.routers.frontend.tls=true"

      # # Edge
      # - "traefik.http.routers.edge.rule=Host(`portainer-edge.lan`)"
      # - "traefik.http.routers.edge.entrypoints=websecure"
      # - "traefik.http.services.edge.loadbalancer.server.port=8000"
      # - "traefik.http.routers.edge.service=edge"
      # - "traefik.http.routers.edge.tls=true" 

volumes:
  portainer_data:

networks:
  proxynet:
    external: true
